version: '2.2'
services:
  postgres:
    image: postgres:14-alpine
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
     - ./pgdata:/var/lib/postgresql/data
    ports:
     - "5432:5432"